# Generated by Django 3.1.7 on 2021-03-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookah_name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=400)),
                ('website', models.URLField(blank=True, max_length=420)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('credit_card', models.BooleanField(default=True)),
                ('summer_terrace', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
            ],
        ),
        migrations.CreateModel(
            name='HookahTobacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookah_tobacco', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HookahType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookah_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HookahImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookah_image', models.ImageField(upload_to='hookahImages')),
                ('hookah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.hookah')),
            ],
        ),
        migrations.AddField(
            model_name='hookah',
            name='hookah_type',
            field=models.ManyToManyField(to='places.HookahType'),
        ),
        migrations.AddField(
            model_name='hookah',
            name='hoookah_tobacco',
            field=models.ManyToManyField(to='places.HookahTobacco'),
        ),
    ]
